version: '3'

services:
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www
      - ./_docker/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: shop_nginx

  app:
    build:
      context: .
      dockerfile: _docker/app/Dockerfile
    volumes:
      - ./:/var/www
    container_name: shop_app
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    volumes:
        - ./tmp/db:/var/lib/postgresql
    environment:
      POSTGRES_PASSWORD: selectel
      POSTGRES_USER: selectel
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    container_name: shop_db

  adminer:
      image: adminer
      restart: always
      ports:
          - "8080:8080"




